title: 'Break the Bubble'
splash_title: 'Break<br> the<br> Bubble'
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: dark_blue
palettes:
  blue:
    sass:
      color: '#4696e5'
  magenta:
    sass:
      color: '#db5c7a'
  purple:
    sass:
      color: '#786dc2'
  pink:
    sass:
      color: '#f072a9'
  dark_blue:
    sass:
      # color: '#26354c'
      color: '#263047'
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - gems/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
  - test/
  - eventbrite.sh
  - test_eventbrite.sh
